service: prettier

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
      - Fn::Join:
        - ':'
        - - arn:aws:lambda
          - Ref: AWS::Region
          - Ref: AWS::AccountId
          - function:${self:service}-${opt:stage, self:provider.stage}-*

functions:
  prettier:
    handler: dist/handler.prettierHandler
    warmup: production
    events:
      - http:
          path: prettier
          method: get
          cors: true
      - http:
          path: prettier
          method: post
          cors: true

plugins:
  - serverless-offline
  - serverless-plugin-warmup

custom:
  warmup:
    prewarm: true
